---
title: "Transmission Modeling"
author: "NB"
date: "2022-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(cmdstanr)
library(reshape2)
library(lubridate)

source("../utils/epi.r")
source("../utils/bayes.R")
source("../utils/plotting.R")
source("../utils/tex.R")
source("../helper/settings.r")
```


## Data

```{r}
col_order <- c("School 1 Intervention (A)", "School 1 Intervention (B)", "School 1 Control", 
               "School 2 Intervention", "School 2 Control")
names(col_order) <- 1:5
J <- length(col_order)

df <- read.csv("../data-clean/redcap-cases.csv") %>%
  mutate(class = recode(class, !!! classes_names),
         school_class = paste(school, class))

full_df <- readRDS("../data-clean/redcap-full-range.rds") %>%
  mutate(class = recode(class, !!! classes_names),
         school_class = paste(school, class))
```

```{r}
# Intervention dates
maskmandate_dates <- full_df %>%
  group_by(school_class) %>%
  arrange(date) %>%
  filter(intervention == "No intervention") %>%
  slice(1) %>%
  ungroup() %>%
  select(school_class, date, day) %>%
  mutate(day = day -1,
         intervention = "Mask\nmandate")

airfilter_dates <- full_df %>%
  group_by(school_class) %>%
  arrange(date) %>%
  filter(intervention == "Air cleaner") %>%
  slice(1) %>%
  ungroup() %>%
  select(school_class, date, day) %>%
  mutate(intervention = "Air\ncleaner")

intervention_dates <- rbind(maskmandate_dates, airfilter_dates) %>%
  mutate(start_day = ifelse(intervention == "Mask\nmandate", -Inf, day),
         end_day = ifelse(intervention == "Air\ncleaner", Inf, day),
         intervention = factor(intervention, levels = c("Mask\nmandate", "Air\ncleaner")),
         x = ifelse(intervention == "Mask\nmandate", 7, 45)) 
```


<!-- ## Simulation -->


<!-- ```{r} -->
<!-- set.seed(12345) -->

<!-- S <- 12 -->
<!-- D <- 52 + S -->
<!-- pop <- 24 -->
<!-- pin <- vp(D+S, F, p_in) -->
<!-- alpha <- -4 -->


<!-- newI <- c() -->
<!-- newN <- c() -->
<!-- SU <- c() -->
<!-- cumI <- c() -->
<!-- cumN <- c() -->

<!-- for (i in 1:1) { -->
<!--   newI[1] <- rexp(1, 1) -->
<!--   cumI[1] <- newI[1] -->
<!--   SU[1] <- pop - cumI[1] -->
<!--   newN[1] <- sum(newI[1] * tail(rev(pin), 1)) -->
<!--   cumN[1] <- newN[1] -->
<!--   for (d in 2:D) { -->
<!--     newI[d] <- invlogit(alpha) * SU[d-1] -->
<!--     cumI[d] <- cumI[d-1] + newI[d] -->
<!--     SU[d] <- pop - cumI[d] -->
<!--     newN[d] <- sum(newI[1:d] * tail(rev(pin), d)) -->
<!--     cumN[d] <- cumN[d-1] + newN[d] -->
<!--   } -->
<!-- } -->

<!-- simDat <- data.frame(day = 1:D, -->
<!--                      infections = cumI, -->
<!--                      cases = cumN, -->
<!--                      susceptibles = SU) -->

<!-- simDat %>% -->
<!--   melt("day") %>% -->
<!--   ggplot(aes(x = day, y = value, color = variable)) + -->
<!--   geom_line() -->
<!-- ``` -->

## Additional Priors

### Incubation period

```{r}
prior_pin_mu_pl <- data.frame(x = seq(1.33,1.93,.01)) %>%
  mutate(y = dnorm(x, p_in_mu_m, p_in_mu_s)) %>%
  ggplot(aes(x = x, y = y)) +
  geom_line() +
  geom_vline(aes(xintercept = p_in_mu_m), linetype = "dotted", color = "blue") +
  labs(x = expression("log "*mu*" of "*p[IN]), y = "Density", title = "a") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  theme_bw2() +
  theme(plot.title = element_text(hjust = 0))

prior_pin_mu_pl

prior_pin_sigma_pl <- data.frame(x = seq(0.3, 0.7, 0.01)) %>%
  mutate(y = dnorm(x, p_in_sigma_m, p_in_sigma_s)) %>%
  ggplot(aes(x = x, y = y)) +
  geom_line() +
  geom_vline(aes(xintercept = p_in_sigma_m), linetype = "dotted", color = "blue") +
  labs(x = expression("log "*sigma*" of "*p[IN]), y = "Density", title = "b") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  theme_bw2() +
  theme(plot.title = element_text(hjust = 0))

prior_pin_sigma_pl


set.seed(12345)

prior_pin <- data.frame(
  lmu = rnorm(4e3, p_in_mu_m, p_in_mu_s),
  lsigma = rnorm(4e3, p_in_sigma_m, p_in_sigma_s)
) %>%
  mutate(pin = map2(lmu, lsigma, function(log_mu, log_sigma) data.frame(x = 0:15, y = vp(15, T, p_in, log_mu, log_sigma)))) %>%
  unnest() 

prior_pin_pl <- prior_pin %>%
  ggplot(aes(x = x, y = y)) +
  stat_lineribbon(point_interval = "mean_qi") +
  scale_fill_brewer() + 
  labs(x = "s (delay in days)", y = expression(p[IN]*" (probability in %)")) +
  ggtitle("c") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  theme_bw2() +
  theme(plot.title = element_text(hjust = 0), legend.position = "none")

prior_pin_pl

comb_prior_pin_pl <- arrangeGrob(prior_pin_mu_pl, prior_pin_sigma_pl, prior_pin_pl, widths = c(5.33, 5.33, 5.33), ncol = 3)

ggsave(plot = comb_prior_pin_pl, filename = "../results/redcap-supp-prior-pin.pdf", width = 16 / cm(1), height = 5 / cm(1))
```


### Seeding phase

```{r}
S <- round(exp(p_in_mu_m + p_in_sigma_m^2 / 2)) * 2
```


## Adjustments

```{r}
adjustments <- readRDS("../fitted-models/multiverse/1/sample-modeling-df.rds") %>%
  select(school_class, school, class, date, median_R_mean, prop_absences) 

r_pl <- adjustments %>%
  filter(school_class == school_class[1]) %>%
  ggplot(aes(x = date, y = median_R_mean)) +
  geom_line(color = "navyblue") +
  scale_x_continuous(expand = expansion(mult = c(0.01,0.01))) +
  scale_y_continuous(expand = expansion(mult = c(0.01,0.01)), limits = c(0, NA)) +
  labs(y = expression(R[t]), x = "Day") +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.title.y = element_text(size = 10))

r_pl
ggsave(file = "../results/adjustments-rt.png", width = 5 / cm(1), h = 3.25 / cm(1))

stud_in_class_pl <- adjustments %>%
  ggplot(aes(x = date, y = prop_absences, color = school_class)) +
  geom_step() +
  scale_x_continuous(expand = expansion(mult = c(0.01,0.01))) +
  scale_y_continuous(expand = expansion(mult = c(0.01,0.01))) +
  labs(y = "Proportion", x = "Day") +
  scale_color_brewer(palette = "Set2") +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.title.y = element_text(size = 10), legend.position = "none")

stud_in_class_pl
ggsave(file = "../results/adjustments-students-in-class.png", width = 5 / cm(1), h = 3.25 / cm(1))


transmission <- read.csv("../data-clean/r-estimates.csv") %>%
  mutate(date = as.Date(date)) %>%
  filter(between(date, as.Date("2021-01-24"), as.Date("2021-03-26")))

cases_pl <- transmission %>%
  ggplot(aes(x = date, y = cases_mean7d)) +
  geom_line(color = "navyblue") +
  scale_x_date(expand = c(0,0), breaks = seq(as.Date("2021-01-24"), as.Date("2021-03-26"), by = "1 week"), date_labels = "%b %d") +
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, 10)) +
  labs(y = "New cases of COVID-19") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), axis.text = element_text(size = 10),
        axis.title = element_text(size = 10), axis.text.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(linewidth = 1))

cases_pl

rt_pl <- transmission %>%
  ggplot(aes(x = date, y = median_R_mean)) +
  geom_line(color = "navyblue") +
  geom_hline(aes(yintercept = 1.), linetype = "dashed") +
  scale_x_date(expand = c(0,0), breaks = seq(as.Date("2021-01-24"), as.Date("2021-03-26"), by = "1 week"), date_labels = "%b %d") +
  scale_y_continuous(limits = c(0, 1.2), breaks = seq(0,1.2, .2)) +
  labs(y = "Reproduction number") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(linewidth = 1))

rt_pl

trans_pl <- arrangeGrob(cases_pl, rt_pl, ncol = 1, heights = c(4.25, 4.75))
ggsave(trans_pl, file = "../results/study-design-transmission.pdf", width = 14 / cm(1), height = 9 / cm(1))
```


## Test model

### Model sample

```{r}
# Data Sample
df_smpl <- readRDS("../fitted-models/multiverse/1/sample-modeling-df.rds")
sDF_smpl <- readRDS("../fitted-models/multiverse/1/sample-modeling-stan-datalist.rds")

# Model
tm <- cmdstan_model("../models/tm_class.stan", cpp_options = list(stan_threads = T))

tmFit <- tm$sample(
  data = sDF_smpl,
  seed = 12345,
  chains = 4,
  iter_warmup = 1e3,
  iter_sampling = 1e3,
  parallel_chains = 4,
  threads_per_chain = 2,
  refresh = 200
)
  
tmFit$summary(c("phi_N", "alpha", "omega", "beta", "mu_p_in", "sigma_p_in", "theta_M", "tau", "theta_l", "theta_A", "gamma")) 
```

### New infections

```{r}
# new infections
new_I <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_new_infections") %>%
  rename(day = row,
         class = col) %>%
  mutate(class = recode(class, !!! col_order),
         class = factor(class, levels = col_order),
         day = day - sDF_smpl$S) %>%
  filter(day >= 1) %>%
  select(-draw) 

new_I %>%
  ggplot(aes(x = day, y = value)) +
  facet_wrap(~class) +
  stat_lineribbon() +
  scale_fill_brewer()
```

### Cumulative incidence

```{r}
cum_I <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_cum_infections") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S) %>%
  mutate(variable = "Cumulative infections")
cum_N <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_cum_cases") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S) %>%
  mutate(variable = "Cumulative cases")
susceptibles <- tidy_draws.CmdStanMCMC_mat(tmFit, "susceptibles") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S) %>%
  mutate(variable = "Susceptibles")

estimated_inc <- rbind(cum_I, cum_N, susceptibles)

estimated_inc %>%
  ggplot(aes(x = day, y = value, fill = variable, color = variable)) +
  facet_wrap(~ school_class) +
  stat_lineribbon(alpha = .2, .width = .95) 
```

### Avoided infections

```{r}
av_inf_masks <- tidy_draws.CmdStanMCMC_mat(tmFit, "avoided_infections_Masks") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S,
         variable = "Mask mandate") 

av_inf_air <- tidy_draws.CmdStanMCMC_mat(tmFit, "avoided_infections_Air") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S,
         variable = "Air cleaner")

rbind(av_inf_masks, av_inf_air) %>%
  group_by(school_class, variable, day) %>%
  mutate(.draw = 1:n()) %>%
  ungroup() %>%
  group_by(variable, .draw) %>%
  summarise(value = -sum(value)) %>%
  ungroup() %>%
  ggplot(aes(x = value, y = variable)) +
  stat_interval() +
  scale_color_brewer()
```


### Coverage

```{r}
# new cases
new_N <- tidy_draws.CmdStanMCMC_mat(tmFit, "estimated_new_cases") %>%
  rename(day = row,
         school_class = col) %>%
  mutate(school_class = recode(school_class, !!! col_order),
         school_class = factor(school_class, levels = col_order),
         day = day - sDF_smpl$S) 

new_N_week <- new_N %>%
  #filter(day > 0) %>%
  left_join(df_smpl %>% select(school_class, week, day, no_school, intervention)) %>%
  filter(!no_school) %>%
  group_by(school_class, intervention, draw) %>%
  summarize(value = sum(value, na.rm = T)) %>%
  ungroup() %>%
  group_by() %>%
  mutate(intervention = factor(intervention, levels = c("None", "Mask mandate", "Air cleaner")))

new_N_week %>%
  ggplot(aes(y = intervention, x = value)) +
  facet_wrap(~ school_class) + 
  stat_interval() +
  stat_pointinterval(point_interval = "mean_qi", fill = "white", shape = 21, .width = NA) +
  geom_point(data = df_smpl %>%
              filter(!no_school) %>%
              group_by(school_class, intervention) %>%
              summarise(value = sum(new_cases)) %>%
              ungroup(),
            color = "red", size = 2, shape = 4) +
  scale_color_brewer() 
```


## Results

```{r}
meta_dat <- data.frame(folders = list.files("../fitted-models/multiverse", full.names = T),
                       dataset = as.numeric(list.files("../fitted-models/multiverse"))) %>%
  arrange(dataset) %>%
  mutate(avoided_file = sapply(folders, list.files, pattern = "avoided-infections", full.names = T),
         inc_file = sapply(folders, list.files, pattern = "incidence", full.names = T),
         sample_file = sapply(folders, list.files, pattern = "sample-modeling-df.rds", full.names = T),
         results_file = sapply(folders, list.files, pattern = "estimation_results", full.names = T))
```

### Estimation results

```{r}
est_results <- meta_dat %>%
  mutate(data = lapply(results_file, readRDS)) %>%
  unnest() %>%
  select(variable, mean, median, sd, mad, q5, q95, rhat, ess_bulk, ess_tail) %>%
  group_by(variable) %>%
  summarize_all(median) %>%
  ungroup() 

est_results %>% 
  filter(variable == c("theta_M", "theta_A")) %>%
  select(-ess_bulk,-rhat) %>%
  mutate_if(is.double, exp)
  
est_results <- est_results %>%
  mutate_if(is.numeric, function(x) tex_sign(round_k(x)))

variable <- c("phi_N", paste0("alpha[", 1:J, "]"), "omega", "mu_p_in", "sigma_p_in", 
              "theta_M", "tau", paste0("theta_l[",1:J,"]"),"theta_A",
              "gamma[1]", "gamma[2]")
variable_name <- c("$\\phi$", 
                   "$\\alpha_{\\textrm{School 1 Intervention (A)}}$", 
                   "$\\alpha_{\\textrm{School 1 Intervention (B)}}$",
                   "$\\alpha_{\\textrm{School 1 Control}}$", 
                   "$\\alpha_{\\textrm{School 2 Intervention}}$", 
                   "$\\alpha_{\\textrm{School 2 Control}}$",
                   "$\\omega$",
                   "$\\mu^{p_{IN}}$", "$\\sigma^{p_{IN}}$", 
                   "$\\theta^M$", "$\\tau$",
                   "$\\theta^M_{\\textrm{School 1 Intervention (A)}}$", 
                   "$\\theta^M_{\\textrm{School 1 Intervention (B)}}$",
                   "$\\theta^M_{\\textrm{School 1 Control}}$", 
                   "$\\theta^M_{\\textrm{School 2 Intervention}}$", 
                   "$\\theta^M_{\\textrm{School 2 Control}}$",
                   "$\\theta^A$", "$\\gamma^{\\textrm{Absences}}$", 
                   "$\\gamma^{\\textrm{Community} R_t}$")
names(variable_name) <- variable

est_results <- est_results %>%
  filter(!(grepl("beta",variable))) %>%
  mutate(parameter = variable,
         parameter = recode(variable, !!! variable_name),
         parameter = factor(parameter, levels = variable_name)) %>%
  select(parameter, mean, q5, q95, rhat, ess_bulk) %>%
  arrange(parameter) %>%
  as.matrix() 

xtable::print.xtable(xtable::xtable(est_results),
                     type = "latex",
                     file = "../results/redcap-supp-estimation-results.tex",
                     sanitize.text.function = identity,
                     include.colnames = F,
                     include.rownames = F,
                     only.contents = T,
                     hline.after = NULL)
```

### New Infections

```{r}
new_inc <- meta_dat %>%
  mutate(data = lapply(inc_file, readRDS)) %>%
  unnest() %>%
  filter(variable == "Infections") %>%
  mutate(school_class = factor(recode(as.integer(school_class), !!! col_order), levels = col_order))

new_inc_mean <- new_inc %>%
  filter(.width == .95) %>%
  group_by(school_class, day) %>%
  summarize(across(c(value, .lower, .upper), median)) %>%
  ungroup()

est_I_pl <- ggplot(new_inc_mean, aes(x = day)) +
  geom_path(aes(y = value), color = RColorBrewer::brewer.pal(9, "Blues")[7]) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), fill = RColorBrewer::brewer.pal(9, "Blues")[7], alpha = .2) +
  facet_wrap(~ school_class) +
  geom_vline(data = intervention_dates, mapping = aes(xintercept = day), linetype = "dotted") +
  geom_vline(data = data.frame(x=1), mapping = aes(xintercept = x), linetype = "dotted", color = "red") +
  scale_x_continuous(expand = c(0,0), breaks = c(-11, seq(1, 51, 10))) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  scale_color_manual(values = cbPalette) +
  labs(y = "Estimated number of new infections", color = "Intervention", title = "a") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), legend.position = "bottom",
        panel.spacing = unit(1, "lines"), plot.title = element_text(hjust = 0)) 

est_I_pl
```

### Cumulative infections

```{r}
cum_inc <- meta_dat %>%
  mutate(data = lapply(inc_file, readRDS)) %>%
  unnest() %>%
  filter(variable %in% c("Cumulative cases", "Cumulative infections", "Susceptibles")) %>%
  mutate(school_class = factor(recode(as.integer(school_class), !!! col_order), levels = c(col_order)))

cum_inc_mean <- cum_inc %>%
  filter(.width == .95) %>%
  group_by(school_class, day, variable) %>%
  summarize(across(c(value, .lower, .upper), median)) %>%
  ungroup()

cum_inc_pl <- ggplot(mapping = aes(x = day)) +
  geom_line(data = cum_inc_mean, mapping = aes(y = value, color = variable, linetype = variable), size = 1) +
  geom_ribbon(data = cum_inc_mean, mapping = aes(ymin = .lower, ymax = .upper, fill = variable), alpha = .2) +
  geom_vline(data = intervention_dates, mapping = aes(xintercept = day), linetype = "dotted") +
  geom_vline(data = data.frame(x=1), mapping = aes(xintercept = x), linetype = "dotted", color = "red") +
  scale_fill_brewer(palette = "Accent") +
  scale_color_brewer(palette = "Accent") +
  facet_wrap(~ school_class) +
  scale_x_continuous(expand = c(0,0), breaks = c(-11, seq(1, 51, 10))) +
  scale_y_continuous(expand = c(0,0)) +
  labs(y = "Estimated number of students", color = "", fill = "", linetype = "", title = "b") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), legend.position = "top",
        panel.spacing = unit(1, "lines"), plot.title = element_text(hjust = 0))

cum_inc_pl

comb_inc_pl <- arrangeGrob(est_I_pl, cum_inc_pl, heights = c(8, 8), ncol = 1)
ggsave(plot = comb_inc_pl, filename = "../results/redcap-supp-results-infections.pdf", width = 16 / cm(1), height = 16 / cm(1))
```

### Coverage

```{r}
# observations
new_inc_obs <- meta_dat %>%
  mutate(observed_data = lapply(sample_file, readRDS)) %>%
  unnest() %>%
  select(school_class, day, new_cases) %>%
  group_by(school_class, day) %>% 
  median_qi(.width = .95) %>%
  ungroup() %>%
  mutate(variable = "Estimates from probabilistic simulation") %>%
  rename(value = new_cases) %>%
  select(school_class, day, variable, value, .lower, .upper) %>%
  mutate(school_class = recode(as.integer(factor(school_class)), !!! col_order))
  
# coverage
coverage_df <- meta_dat %>%
  mutate(data = lapply(inc_file, readRDS)) %>%
  unnest() %>%
  filter(variable == "Estimated cases") %>%
  filter(.width == .95) %>%
  group_by(school_class, day) %>%
  summarize(across(c(value, .lower, .upper), median)) %>%
  ungroup() %>%
  #filter(day >= 1) %>%
  mutate(variable = "Estimates from transmission model") %>%
  mutate(school_class = recode(as.integer(school_class), !!! col_order)) %>%
  rbind(new_inc_obs) %>%left_join(full_df %>%
              select(school_class, day, intervention, no_school)) %>%
  filter(!no_school) %>%
  group_by(school_class, intervention, variable) %>%
  summarise(across(c(value, .lower, .upper), sum, na.rm = T)) %>%
  ungroup()

coverage_df_pl <- coverage_df %>%
  ggplot(aes(y = intervention, color = variable)) +
  facet_wrap(~ school_class) + 
  geom_errorbar(mapping = aes(xmin = .lower, xmax = .upper), width = .25, position = position_dodge(width = .25)) +
  geom_point(mapping = aes(x = value, shape = variable, color = variable), size = 2, position = position_dodge(width = .25)) +
  scale_color_manual(values = c("blue", "black")) +
  labs(x = "Estimated number of cases") +
  theme_bw2() +
  theme(legend.title = element_blank(), axis.title.y = element_blank(), legend.position = "top")

coverage_df_pl
save_plot(coverage_df_pl, pdf_file = "../results/redcap-supp-results-coverage.pdf", w = 16, h = 8)
```


### Avoided infections

```{r}
avoided_df <- meta_dat %>%
  mutate(data = lapply(avoided_file, readRDS)) %>%
  unnest() %>%
  mutate(variable = ifelse(variable == "Masks", "Mask mandate", "Air cleaner"),
         variable = factor(variable, levels = c("Mask mandate", "Air cleaner")),
         school_class = recode(as.integer(school_class), !!! col_order))

avoided_df_sum <- avoided_df %>%
  select(dataset, variable, school_class, draw, value) %>%
  group_by(dataset, variable, draw) %>%
  summarize(value = sum(value)) %>%
  ungroup() %>%
  select(-draw) %>%
  group_by(dataset, variable) %>%
  mean_qi(.width = c(0.5, 0.8, 0.95)) %>%
  ungroup() %>%
  group_by(variable, .width) %>%
  summarise(value = median(value),
            .lower = median(.lower),
            .upper = median(.upper)) %>%
  ungroup() 

av_inf_tot_pl <- avoided_df_sum %>%
  arrange(desc(.width)) %>%
  ggplot(aes(xmin = .lower, xmax = .upper, ymin = 0, ymax = 2, fill = factor(.width, levels = rev(c(.5, .8, .95))))) +
  geom_rect() +
  geom_point(aes(x = value, y = 1), size = 4, fill = "white", shape = 21) +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  facet_wrap(~ variable) +
  scale_fill_brewer() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(breaks = seq(-10, 20, 5)) +
  labs(x = "Estimated number of avoided infections", fill = "CrI", title = "c") +
  theme_bw2() +
  theme(axis.title.y = element_blank(), legend.position = "right", 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.title = element_text(hjust = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  
av_inf_tot_pl

save_plot(av_inf_tot_pl, pdf_file = "../results/redcap-results.pdf", w = 16, h = 3)
```

```{r}
avoided_df_sum_by_d <- avoided_df %>%
  select(dataset, variable, school_class, draw, value) %>%
  group_by(dataset, variable, draw) %>%
  summarize(value = sum(value)) %>%
  ungroup() %>%
  select(-draw) %>%
  group_by(dataset, variable) %>%
  mean_qi(.width = c(0.5, 0.8, 0.95)) %>%
  ungroup() %>%
  group_by(variable, .width) %>%
  arrange(value) %>%
  mutate(order = 1:n()) %>%
  ungroup()

av_inf_tot_by_d_pl <- ggplot(data = avoided_df_sum_by_d, mapping = aes(y = order)) +
  geom_ribbon(mapping = aes(xmin = .lower, xmax = .upper, fill = factor(.width, levels = c(.95, .8, .5)))) +
  geom_point(mapping = aes(x = value), size = 2, fill = "white", shape = 21) +
  geom_vline(mapping = aes(xintercept = 0), linetype = "dotted") + 
  facet_wrap(~ variable) +
  scale_fill_brewer() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Estimated number of avoided infections", fill = "CrI", alpha = "CrI") +
  theme_bw2() +
  theme(axis.title.y = element_blank(), plot.title = element_text(hjust = 0), legend.position = "none",
        axis.text.y = element_blank(), axis.ticks.y = element_blank())

av_inf_tot_by_d_pl

save_plot(av_inf_tot_by_d_pl, pdf_file = "../results/redcap-supp-results-by-dataset.pdf", w = 16, h = 18)
```