---
title: "Transmission Modeling"
author: "NB"
date: "2022-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(cmdstanr)
library(reshape2)
library(lubridate)

source("../utils/epi.r")
source("../utils/bayes.R")
source("../utils/plotting.R")
```


## Data

```{r}
df <- read_csv("../data-clean/redcap.csv") %>%
  filter(!no_school) %>%
  mutate(new_cases = new_confirmed + new_symptomatic + new_unknown,
         new_suspected = new_symptomatic + new_unknown,
         cum_cases = cum_confirmed + cum_symptomatic + cum_unknown,
         cum_suspected = cum_symptomatic + cum_unknown) %>%
  rename(population = n_class,
         absences = n_tot_absent) %>%
  group_by(school, class) %>%
  arrange(date) %>%
  mutate(day = 1:n()) %>%
  ungroup() 

r_est <- read_csv("../data-clean/r-estimates.csv")

df_school <- df %>%
  group_by(school, day, week, date, weekend) %>%
  summarize(across(c(new_cases, cum_cases, 
                     new_suspected, cum_suspected, 
                     new_confirmed, cum_confirmed, 
                     population, absences), sum)) %>%
  ungroup() %>%
  mutate(prop_absences = absences / population) %>%
  left_join(r_est)
```

```{r}
df_comp <- df_school %>%
  select(school, date, day, cum_suspected, cum_confirmed) %>%
  melt(c("school", "date", "day")) %>%
  mutate(variable = ifelse(grepl("confirmed", variable), "Confirmed", ifelse(grepl("suspected", variable), "Suspected", "All cases"))) %>%
  mutate(type = "Observed")

df_comp_new <- df_school %>%
  select(school, date, day, new_cases, new_confirmed, new_suspected) %>%
  melt(c("school", "date", "day")) %>%
  mutate(variable = ifelse(grepl("confirmed", variable), "Confirmed", ifelse(grepl("suspected", variable), "Suspected", "All cases"))) %>%
  mutate(type = "Observed")

maskmandate_dates <- df %>%
  group_by(school) %>%
  arrange(date) %>%
  filter(intervention == "None") %>%
  slice(1) %>%
  ungroup() %>%
  select(school, date, day) %>%
  mutate(day = day -1,
         intervention = "Mask mandate ended")

airfilter_dates <- df %>%
  group_by(school) %>%
  arrange(date) %>%
  filter(intervention == "Air filter") %>%
  slice(1) %>%
  ungroup() %>%
  select(school, date, day) %>%
  mutate(intervention = "Air filter started")

intervention_dates <- rbind(maskmandate_dates, airfilter_dates) 
```


## Descriptives

```{r}
df %>%
  group_by(school, class) %>%
  summarize(cum_cases = max(cum_cases),
            population = max(population)) %>%
  ungroup() %>%
  group_by(school) %>%
  summarize(sum(cum_cases)/sum(population))

df %>%
  group_by(school, class) %>%
  summarize(cum_confirmed_cases = max(cum_confirmed),
            cum_suspected_cases = max(cum_confirmed + cum_symptomatic + cum_unknown)) %>%
  ungroup() %>%
  group_by(school) %>%
  summarize(sum(cum_confirmed_cases) / sum(cum_suspected_cases))

df_school %>%
  select(school, day, cum_cases, cum_suspected, cum_confirmed, population) %>%
  melt(c("school", "day")) %>%
  ggplot(aes(x = day, y = value, color = variable)) +
  geom_path() +
  facet_wrap(~ school) +
  scale_y_continuous(expand= expansion(add = c(0,0.5))) +
  scale_x_continuous(expand = c(0,0))

df_school %>%
  select(school, day, new_suspected, new_confirmed) %>%
  melt(c("school", "day")) %>%
  ggplot(aes(x = day, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ school)
  
df_school %>%
  ggplot(aes(x = new_cases)) +
  geom_histogram()
  

df_school %>%
  select(school, day, prop_contagious, prop_absences) %>%
  melt(c("school", "day")) %>%
  ggplot(aes(x = day, y = value, color = variable)) +
  geom_line() +
  facet_wrap(~ school) +
  scale_y_continuous(expand= c(0,0), limits = c(0,1)) +
  scale_x_continuous(expand = c(0,0))

r_est %>%
  filter(between(date, min(df_school$date), max(df_school$date))) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = median_R_mean)) +
  geom_line(aes(y = median_R_mean + median_R_SD), linetype = "dashed") +
  geom_line(aes(y = median_R_mean - median_R_SD), linetype = "dashed") +
  geom_vline(data = intervention_dates, mapping = aes(xintercept = date), linetype = "dotted", color = "red") +
  geom_hline(aes(yintercept = 1.0), linetype = "dotted", color = "blue")
```


## Simulation


```{r}
set.seed(12345)

S <- 12
D <- 52 + S
pop <- 55
pin <- vp(D+S, F, p_in)
alpha <- -5


newI <- c()
newN <- c()
SU <- c()
cumI <- c()
cumN <- c()

for (i in 1:1) {
  newI[1] <- rexp(1, 1)
  cumI[1] <- newI[1]
  SU[1] <- pop - cumI[1]
  newN[1] <- sum(newI[1] * tail(rev(pin), 1))
  cumN[1] <- newN[1]
  for (d in 2:D) {
    newI[d] <- invlogit(alpha) * SU[d-1]
    cumI[d] <- cumI[d-1] + newI[d]
    SU[d] <- pop - cumI[d]
    newN[d] <- sum(newI[1:d] * tail(rev(pin), d))
    cumN[d] <- cumN[d-1] + newN[d]
  }
}

simDat <- data.frame(day = 1:D,
                     infections = cumI,
                     cases = cumN,
                     susceptibles = SU)

simDat %>%
  melt("day") %>%
  ggplot(aes(x = day, y = value, color = variable)) +
  geom_line()
```


## Modeling

### Stan Data

```{r}
sDF <- list(
  L = 2,
  D = nrow(df_school) / 2,
  S = round(exp(p_in_mu_m + p_in_sigma_m^2 / 2)) * 2,
  new_cases = df_school %>%
    select(school, day, new_cases) %>%
    spread(school, new_cases) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  new_confirmed_cases = df_school %>%
    select(school, day, new_confirmed) %>%
    spread(school, new_confirmed) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  new_suspected_cases = df_school %>%
    select(school, day, new_suspected) %>%
    spread(school, new_suspected) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  population = c(df_school$population[df_school$school=="School 1"][1],
                 df_school$population[df_school$school=="School 2"][1]),
  prop_absences = df_school %>%
    select(school, day, prop_absences) %>%
    spread(school, prop_absences) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  medianRest_mean = df_school %>%
    select(school, day, median_R_mean) %>%
    spread(school, median_R_mean) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  medianRest_sd = df_school %>%
    select(school, day, median_R_SD) %>%
    spread(school, median_R_SD) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  maskmandate = df %>%
    select(school, day, maskmandate) %>%
    group_by(school, day) %>%
    slice(1) %>%
    ungroup() %>%
    spread(school, maskmandate) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  airfilter = df %>%
    select(school, day, airfilter) %>%
    group_by(school, day) %>%
    slice(1) %>%
    ungroup() %>%
    spread(school, airfilter) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  weekend = df_school %>%
    select(school, day, weekend) %>%
    spread(school, weekend) %>%
    select(-day, `School 1`, `School 2`) %>%
    as.matrix(),
  p_in_mu_m = p_in_mu_m,
  p_in_mu_s = p_in_mu_s,
  p_in_sigma_m = p_in_sigma_m,
  p_in_sigma_s = p_in_sigma_s
)

# add data for seeding phase
sDF$maskmandate <- rbind(matrix(1, nrow = sDF$S, ncol = sDF$L), sDF$maskmandate)
sDF$airfilter <- rbind(matrix(0, nrow = sDF$S, ncol = sDF$L), sDF$airfilter)
sDF$medianRest_mean <- rbind(r_est %>% 
                               filter(between(date, min(df_school$date) - sDF$S, min(df_school$date) - 1)) %>% 
                               arrange(date) %>%
                               mutate(median_R_mean2 = median_R_mean) %>%
                               select(median_R_mean, median_R_mean2) %>%
                               as.matrix(),
                             sDF$medianRest_mean)
sDF$medianRest_sd <- rbind(r_est %>% 
                               filter(between(date, min(df_school$date) - sDF$S, min(df_school$date) - 1)) %>% 
                               arrange(date) %>%
                               mutate(median_R_mean2 = median_R_mean) %>%
                               select(median_R_mean, median_R_mean2) %>%
                               as.matrix(),
                             sDF$medianRest_sd)
sDF$weekend <- rbind(r_est %>% 
                       filter(between(date, min(df_school$date) - sDF$S, min(df_school$date) - 1)) %>% 
                       arrange(date) %>%
                       mutate(weekend = ifelse(weekdays(date) %in% c("Saturday", "Sunday"), 1, 0),
                              weekend2 = weekend) %>% 
                       arrange(date) %>%
                       select(weekend, weekend2) %>%
                       as.matrix(),
                     sDF$weekend)
```

### Model

```{r}
tm <- cmdstan_model("../models/tm_school_modified.stan", cpp_options = list(stan_threads = T))
#tm <- cmdstan_model("../models/tm_school.stan")
tmFit <- tm$sample(
  data = sDF,
  seed = 12345,
  chains = 4,
  iter_warmup = 1e3,
  iter_sampling = 1e3,
  parallel_chains = 4,
  threads_per_chain = 2,
  refresh = 200
)

tmFit$save_output_files(dir = "../fitted-models", basename = "tm_school")

tmFit$summary(c("phi_N", "alpha", "mu_p_in", "sigma_p_in",
                "theta_M", "theta_A",
                "gamma", "mult", "p"))
```

### Model check

```{r}
# Prior vs posterior checks
tidy_draws.CmdStanMCMC(tmFit, "alpha") %>% 
  melt(c(".chain", ".draw", ".iteration")) %>%
  ggplot(aes(x = value)) +
  geom_density() +
  facet_wrap(~ variable) +
  geom_density(data = data.frame(value = rst(4e3, -4, 2, 3)), color = "blue")

tidy_draws.CmdStanMCMC(tmFit, "theta_M") %>% 
  melt(c(".chain", ".draw", ".iteration")) %>%
  ggplot(aes(x = value)) +
  facet_wrap(~ variable) +
  geom_density() +
  geom_density(data = data.frame(value = rst(4e3, 0, 1, 7)), color = "blue")

tidy_draws.CmdStanMCMC(tmFit, "theta_A") %>% 
  melt(c(".chain", ".draw", ".iteration")) %>%
  ggplot(aes(x = value)) +
  facet_wrap(~ variable) +
  geom_density() +
  geom_density(data = data.frame(value = rst(4e3, 0, 1, 7)), color = "blue")
```

### Fit

#### New cases

```{r}
comp_I <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_new_infections") %>%
  mutate(variable = "Expected infections") 

comp_N <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_new_cases") %>%
  mutate(variable = "Expected cases") 

est_comp <- rbind(comp_I, comp_N) %>%
  rename(day = row,
         school = col) %>%
  mutate(school = paste("School", school),
         day = day - sDF$S) %>%
  select(-draw) %>%
  group_by(school, day, variable) %>%
  mean_qi() %>%
  ungroup()

new_inc_pl <- ggplot(mapping = aes(x = day)) +
  geom_line(data = est_comp, mapping = aes(y = value, color = variable), size = 1) +
  geom_ribbon(data = est_comp, mapping = aes(ymin = .lower, ymax = .upper, fill = variable), alpha = .2) +
  geom_bar(data = df_comp_new %>% 
             filter(variable != "All cases"),
           mapping = aes(y = -value, fill = variable), stat = "identity", position = "stack", size = 1) +
  geom_vline(data = intervention_dates, mapping = aes(xintercept = day), linetype = "dotted") +
  geom_vline(data = data.frame(x=1), mapping = aes(xintercept = x), linetype = "dotted", color = "red") +
  geom_hline(data = data.frame(y=0), mapping = aes(yintercept = y)) +
  scale_fill_brewer(palette = "Accent") +
  scale_color_brewer(palette = "Accent") +
  facet_wrap(~ school) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(add = c(0.1,0.1)), labels = function(x) abs(x), breaks = seq(-7, 7, 1)) +
  labs(y = "Incidence", color = "", fill = "", linetype = "") +
  theme_bw2() #+
  #theme(axis.title.x = element_blank(), legend.position = "none")

new_inc_pl

save_plot(new_inc_pl, "../results/fitted-new-incidence.pdf", w = 16, h = 10)
```

#### Cumulative cases

```{r}
comp_I <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_cum_infections") %>%
  mutate(variable = "Infections") 

comp_N <- tidy_draws.CmdStanMCMC_mat(tmFit, "mu_cum_cases") %>%
  mutate(variable = "Cases") 

comp_S <- tidy_draws.CmdStanMCMC_mat(tmFit, "susceptibles") %>%
  mutate(variable = "Susceptibles") 

est_comp <- rbind(comp_I, comp_N, comp_S) %>%
  rename(day = row,
         school = col) %>%
  mutate(school = paste("School", school),
         day = day - sDF$S) %>%
  select(-draw) %>%
  group_by(school, day, variable) %>%
  mean_qi() %>%
  ungroup() %>%
  mutate(type = "Estimated")

df_comp_wSeed <- df_comp %>% 
  select(-date) %>%
  filter(variable %in% c("Suspected", "Susceptibles")) %>%
  left_join(est_comp %>%
    select(school, day, variable, value) %>%
    filter(variable %in% c("Cases", "Susceptibles")) %>%
    filter(day == 1) %>%
    mutate(value = round(value),
           type = "Observed") %>%
    rename(seed_value = value) %>%
    select(-day)) %>%
  mutate(value = value + ifelse(variable == "Susceptibles" & day == 1, -seed_value, seed_value))

cum_inc_pl <- ggplot(mapping = aes(x = day)) +
  geom_line(data = est_comp, mapping = aes(y = value, color = variable, linetype = type), size = 1) +
  geom_ribbon(data = est_comp, mapping = aes(ymin = .lower, ymax = .upper, fill = variable), alpha = .2) +
  #geom_line(data = df_comp_wSeed, mapping = aes(y = value, color = variable, linetype = type), size = 1) +
  geom_vline(data = intervention_dates, mapping = aes(xintercept = day), linetype = "dotted") +
  geom_vline(data = data.frame(x=1), mapping = aes(xintercept = x), linetype = "dotted", color = "red") +
  scale_fill_brewer(palette = "Accent") +
  scale_color_brewer(palette = "Accent") +
  facet_wrap(~ school) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(y = "Cumulative incidence", color = "", fill = "", linetype = "") +
  theme_bw2() +
  theme(axis.title.x = element_blank())

cum_inc_pl

save_plot(cum_inc_pl, "../results/fitted-cum-incidence.pdf", w = 16, h = 10)
```


### Avoided infections

```{r}
avoided_I_masks <- tidy_draws.CmdStanMCMC_mat(tmFit, "avoided_infections_Masks") %>%
  mutate(variable = "Mask mandate")
avoided_I_air <- tidy_draws.CmdStanMCMC_mat(tmFit, "avoided_infections_Air") %>%
  mutate(variable = "Air filter")

avoided_I <- rbind(avoided_I_masks, avoided_I_air) %>%
  group_by(col, draw, variable) %>%
  summarize(value = -sum(value)) %>%
  ungroup() %>%
  rename(school = col) %>%
  mutate(school = paste("School", school))

avoided_I_mean <- avoided_I %>%
  group_by(school, variable) %>%
  summarize(value = mean(value)) %>%
  ungroup() 

av_inf_pl <- ggplot(mapping = aes(x = value, y = variable)) +
  stat_interval(data = avoided_I) +
  geom_point(data = avoided_I_mean, size = 2, fill = "white", shape = 21) +
  geom_vline(data = data.frame(x = 0), mapping = aes(xintercept = 0), linetype = "dotted") + 
  facet_wrap(~ school) +
  scale_color_brewer() +
  labs(x = "Number of avoided infections", color = "CrI") +
  theme_bw2() +
  theme(axis.title.y = element_blank())

av_inf_pl

save_plot(av_inf_pl, "../results/avoided-incidence.pdf", w = 12, h = 4)
```