---
title: "Palas"
author: "NB"
date: "2022-08-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(tidybayes)
library(reshape2)
library(lubridate)
library(rstanarm)
library(texreg)
library(gridExtra)
library(ggpubr)
library(ggridges)
library(gg.layers)
library(xtable)
library(psych)

source("../utils/plotting.R")
source("../utils/tex.R")
source("../helper/settings.r")
```


## Data

```{r}
df <- read_csv("../data-clean/palas.csv") %>%
  mutate(weekday = factor(weekday, levels = paste0(c("Mon", "Tues", "Wednes", "Thurs", "Fri"), "day")),
         intervention = factor(intervention, levels = c("Mask mandate", "No intervention", "Air cleaner"))) 

df_daily <- df %>%
  group_by(school, date, week, weekday, intervention) %>%
  summarize(aer = harmonic.mean(aer), 
            across(c(n, co2ppm, rav, rh, tc, cn1cm, pm1mugm, pm25mugm, pm4mugm, pm10mugm), ~ mean(.x, na.rm = T))) %>%
  ungroup() %>%
  group_by(school) %>%
  arrange(date) %>%
  mutate(day = 1:n()) %>%
  ungroup()

vars <- c("co2ppm", "rh", "tc", "aer", "rav", "cn1cm", "pm1mugm", "pm25mugm", "pm4mugm", "pm10mugm")
vars_labels <- c("CO[2]~(ppm)", "Relative~humidity~('%')", "Temperature~(degree*C)", 
                 "Air~exchange~rate~(changes/h)", "Rebreathed~air~volume~(l/min)",
                 "CN~(1/cm^3)", "PM[1]~(mu*gm^{-3})", "PM[2.5]~(mu*gm^{-3})", "PM[4]~(mu*gm^{-3})", "PM[10]~(mu*gm^{-3})")
names(vars_labels) <- vars
vars_labels_no_units <- c("CO[2]", "Relative~humidity", "Temperature", "Air~exchange~rate", "Rebreathed~air~volume",
                          "CN", "PM[1]", "PM[2.5]", "PM[4]", "PM[10]")
names(vars_labels_no_units) <- vars
```


## Descriptives

```{r}
# co2 overall
df_daily %>%
  summarize(paste(round(mean(co2ppm)), round(sd(co2ppm)), sep = " +/- "))

# co2 by daytime
co2_hourly <- df %>%
  mutate(time_h = hour(time)) %>%
  group_by(school, time_h) %>%
  summarize(mean = mean(co2ppm),
            lower = quantile(co2ppm, 0.25),
            upper = quantile(co2ppm, 0.75),
            n_data = n()) %>%
  ungroup() 

co2_hourly %>%
  ggplot(aes(x = time_h, y = n_data, fill = school)) +
  geom_bar(stat = "identity", position = position_dodge())

co2_hourly %>%
  filter(n_data >= 100) %>%
  ggplot(aes(x = time_h, group = school, color = school)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .2, position = position_dodge2(width = .2)) +
  geom_point(aes(y = mean), position = position_dodge2(width = .2)) +
  geom_line(aes(y = mean)) +
  scale_color_brewer(palette = "Set2") +
  scale_x_continuous(breaks = seq(7, 16, 1)) +
  labs(x = "Daytime (h)", y = "CO2 (Mean and IQR)") +
  theme_bw() +
  theme(legend.position = c(0.9,0.9), legend.title = element_blank())

# co2 and particle concentrations between study conditions
df_daily %>%
  group_by(intervention) %>%
  summarise(across(c(co2ppm, cn1cm), ~ paste(round(mean(.x)), round(sd(.x)), sep = " +/- ")),
            across(c(pm1mugm, pm25mugm, pm4mugm, pm10mugm), ~ paste(round(mean(.x), 1), round(sd(.x), 1), sep = " +/- ")))


# boxplots
boxplots <- df_daily %>%
  select(school, intervention, co2ppm, rh, tc, aer, rav, cn1cm, pm1mugm, pm25mugm, pm4mugm, pm10mugm) %>%
  melt(c("school", "intervention")) %>%
  ggplot(aes(color = intervention, y = value, x = school)) +
  facet_wrap(~ variable, scales = "free_y", ncol = 2, dir = "v", labeller = as_labeller(vars_labels, label_parsed)) +
  #geom_boxplot(outlier.size = 1) +
  geom_boxplot2(width = 0.8, width.errorbar = 0.1) +
  scale_color_manual(values = intervention_col) +
  labs(color = "Intervention") +
  theme_bw2() +
  theme(legend.position = "top", axis.title = element_blank(), 
        legend.title = element_blank())

boxplots

save_plot(boxplots, "../results/palas-supp-descriptives.pdf", w = 16, h = 14)

boxplots_main <- df_daily %>%
  select(school, intervention, cn1cm, pm1mugm, pm25mugm, pm4mugm, pm10mugm) %>%
  melt(c("school", "intervention")) %>%
  ggplot(aes(color = intervention, y = value, x = variable)) +
  facet_wrap(~ variable, scales = "free", nrow = 1, labeller = as_labeller(vars_labels, label_parsed)) +
  geom_boxplot2(width = 0.8, width.errorbar = 0.1) +
  scale_color_manual(values = intervention_col) +
  labs(color = "Intervention", title = "a") +
  theme_bw2() +
  theme(axis.title = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.title = element_blank(), legend.position = c(.5, 1.31), legend.key.height = unit(.3, "cm"),
        legend.key.width = unit(.2, "cm"), plot.title.position = "plot",
        legend.direction = "horizontal",  
        legend.text = element_text(size = 8))

boxplots_main
save_plot(boxplots_main, "../results/palas-descriptives.pdf", w = 16, h = 4.25)
```

## Check ventilation duration

```{r}
vent_dur <- readRDS("../data-clean/ventilation-duration.rds") %>%
  mutate(intervention = factor(intervention, levels = c("No intervention", "Mask mandate", "Air cleaner")))

seed0 <- 12345
vm <- stan_glm(prop_vent ~ intervention + weekday, data = vent_dur, seed = seed0)
summary(vm)

bayesplot::mcmc_intervals(vm) +
  geom_vline(aes(xintercept = 0))

as.data.frame(vm) %>%
  select(`interventionMask mandate`, `interventionAir cleaner`) %>%
  set_names(c("Mask mandate", "Air cleaner")) %>%
  gather() %>%
  group_by(key) %>%
  mean_qi() %>%
  ungroup() %>%
  mutate(across(c(value, .lower, .upper), round, 2))
```

## Linear models


```{r}
# log data
df_daily_log <- df_daily %>%
  mutate(across(c(cn1cm, pm1mugm, pm25mugm, pm4mugm, pm10mugm, n, aer), log)) %>%
  mutate(intervention = factor(intervention, levels = c("No intervention", "Mask mandate", "Air cleaner")))

seed0 <- 12345
draws <- list()
particle_vars <- c("cn1cm", "pm1mugm", "pm25mugm", "pm4mugm", "pm10mugm")

for (i in 1:length(particle_vars)) {
  f <- as.formula(paste0(particle_vars[[i]], "~ school + weekday + intervention + n + aer"))
  m <- stan_glm(f, data = df_daily_log, seed = seed0)
  draws[[i]] <- as.data.frame(m)
}

draws_filt <- lapply(draws, function(D) dplyr::select(D, `interventionMask mandate`, `interventionAir cleaner`))
draws_filt <- do.call(rbind, draws_filt) %>%
  mutate(outcome = factor(rep(particle_vars, each = nrow(draws[[i]])), levels = rev(particle_vars))) %>%
  set_names(c("Mask mandate", "Air cleaner", "outcome")) %>%
  select(outcome, `Mask mandate`, `Air cleaner`) %>%
  melt("outcome") %>%
  mutate(value = abs(100 * (exp(value) - 1)))

# # all for supplements
# effects_env <- draws_filt %>%
#   mutate(outcome = recode(as.character(outcome), !!! vars_labels_no_units),
#          outcome = factor(outcome, levels = rev(vars_labels_no_units))) %>%
#   ggplot(aes(y = outcome, color = variable, x = value)) +
#   stat_pointinterval(point_interval = "mean_qi", position = position_dodge(width = .5), 
#                      fill = "white", shape = 21, .width = c(.5, .8, .95)) +
#   labs(color = "Intervention", x = "Estimated change in z-score") +
#   scale_color_manual(values = cbPalette) +
#   scale_y_discrete(labels = scales::parse_format()) +
#   geom_vline(aes(xintercept = 0), linetype = "dotted") +
#   theme_bw2() +
#   theme(axis.title.y = element_blank(), legend.position = "top", legend.title = element_blank())
# 
# effects_env
# 
# save_plot(effects_env, "../results/palas-supp-results.pdf", w = 12, h = 11)

# supplementary table
effects_tbl <- draws_filt %>%
  mutate(outcome = recode(as.character(outcome), !!! vars_labels_no_units),
         outcome = factor(outcome, levels = rev(vars_labels_no_units))) %>%
  rename(intervention = variable) %>%
  group_by(outcome, intervention) %>%
  mean_qi() %>%
  ungroup() %>%
  filter(.width == .95) %>%
  select(outcome, intervention, value, .lower, .upper) %>%
  melt(c("outcome", "intervention")) %>%
  dcast(outcome ~ intervention + variable) %>%
  mutate_if(is.numeric, round_k) %>%
  mutate(across(-outcome, tex_sign)) %>%
  arrange(-row_number()) %>%
  mutate(outcome = c("CN", "PM$_{1}$", "PM$_{2.5}$", "PM$_{4}$", "PM$_{10}$"),
         space = "") %>%
  select(outcome, matches("Mask"), space, matches("Air")) %>%
  as.matrix() %>%
  xtable() %>%
  print.xtable(
    file = "../results/palas-supp-estimation-results.tex",
    type = "latex",
    sanitize.text.function = identity,
    include.colnames = F,
    include.rownames = F,
    only.contents = T,
    hline.after = NULL)

# selected for manuscript
effects_env_main <- draws_filt %>%
  #filter(outcome %in% c("cn1cm", "pm1mugm", "pm4mugm")) %>%
  mutate(outcome = factor(outcome, levels = (c("cn1cm", "pm1mugm", "pm25mugm", "pm4mugm", "pm10mugm")))) %>%
  ggplot(aes(y = variable, color = variable, x = value)) +
  stat_pointinterval(point_interval = "mean_qi", fill = "white", shape = 21, .width = c(.5, .8, .95)) +
  facet_wrap(~ outcome, nrow = 1, labeller = as_labeller(vars_labels_no_units, label_parsed)) +
  labs(color = "Intervention", x = "Estimated reduction (%)", title = "b") +
  scale_color_manual(values = cbPalette) +
  scale_x_continuous(limits = c(0,100)) +
  #geom_vline(aes(xintercept = 0), linetype = "dotted") +
  theme_bw2() +
  theme(axis.title.y = element_blank(), legend.position = "none", 
        axis.ticks.y = element_blank(), axis.text.y = element_blank(),
        legend.title = element_blank(), plot.title.position = "plot")

effects_env_main
save_plot(effects_env_main, "../results/palas-results.pdf", w = 16, h = 3)
```
