---
title: "descriptives-redcap.rmd"
author: "NB"
date: "2022-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries

```{r}
library(tidyverse)
library(tidybayes)
library(lubridate)
library(reshape2)
library(xtable)

source("../utils/epi.r")
source("../utils/plotting.r")
source("../helper/settings.r")
```


## Data

```{r}
df <- read_csv("../data-clean/redcap-cases.csv") %>%
  filter(!is_teacher) %>% # ignore cases from teachers 
  select(-is_teacher) %>%
  mutate(class = factor(class, levels = c("Study (A)", "Study (B)", "Study", "Control")))

full_df <- readRDS("../data-clean/redcap-full-range.rds")

absences_df <- read_csv("../data-clean/redcap-absences.csv")

sim_df <- data.frame(folders = list.files("../fitted-models/multiverse", full.names = T),
                     dataset = as.numeric(list.files("../fitted-models/multiverse"))) %>%
  arrange(dataset) %>%
  rowwise() %>%
  mutate(sample_file = sapply(folders, list.files, pattern = "sample.rds", full.names = T)) %>%
  mutate(sample = lapply(sample_file, readRDS)) %>%
  unnest() 

sim_modeling_df <- data.frame(folders = list.files("../fitted-models/multiverse", full.names = T),
                     dataset = as.numeric(list.files("../fitted-models/multiverse"))) %>%
  arrange(dataset) %>%
  rowwise() %>%
  mutate(sample_file = sapply(folders, list.files, pattern = "sample-modeling-df.rds", full.names = T)) %>%
  mutate(sample = lapply(sample_file, readRDS)) %>%
  unnest()
```


## Descriptives

### Total cases

```{r}
total_freq <- sim_df  %>%
  left_join(full_df %>% 
              rename(date_start = date) %>%
              select(school, class, date_start, intervention)) %>%
  group_by(dataset, school, class, intervention) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  select(-dataset) %>%
  group_by(school, class, intervention) %>%
  mean_qi() %>%
  ungroup() %>%
  mutate(class = factor(class, levels = c("Study (A)", "Study (B)", "Study", "Control"))) 

total_freq %>% 
  group_by(intervention) %>% 
  summarise(across(c(n, .lower, .upper), function(x) round(sum(x), 0))) %>%
  ungroup()

total_freq_pl <- total_freq %>%
  mutate(class = recode(class, !!! classes_names)) %>%
  ggplot(aes(x = class, color = intervention)) +
  #geom_bar(aes(y = max), position = "stack", stat = "identity", width = .5, alpha = .75) +
  geom_errorbar(aes(ymin = .lower, ymax = .upper), 
                width = .4, size = 1, position = position_dodge2(width = .4)) +
  geom_point(aes(y = n), 
             size = 2, shape = 21, fill = "white", position = position_dodge2(width = .4)) +
  #scale_fill_manual(values = rev(intervention_col)) +
  scale_color_manual(values = (intervention_col)) +
  facet_wrap(~ school, scales = "free_x")  +
  scale_y_continuous(expand = expansion(add = c(0.75)), limits = c(0, NA)) +
  labs(x = "Class", y = "Estimated number of cases", title = "a") +
  theme_bw2() +
  theme(legend.position = "top", plot.title = element_text(hjust = 0),
        legend.title = element_blank(), axis.title.x = element_blank())

total_freq_pl
``` 

### New cases

```{r}
col_order <- c("School 1 Intervention (A)", "School 1 Intervention (B)", "School 1 Control", 
               "School 2 Intervention", "School 2 Control")

cases_time_pl <- sim_modeling_df %>%
  group_by(school_class, school, class, date, intervention, weekend, no_school) %>%
  summarise(new_cases = mean(new_cases)) %>%
  ungroup() %>%
  mutate(intervention = as.character(intervention), 
         intervention = ifelse(weekend == 1, "Weekend", ifelse(no_school, "Vacation", intervention)),
         intervention = ifelse(school == "School 2" & date >= as.Date("2022-03-19"), "", intervention),
         intervention = factor(intervention, levels = c("Mask mandate", "No intervention", "Air cleaner", 
                                                        "Vacation", "Weekend", "")),
         class = recode(class, !!! classes_names),
         school_class = factor(paste(school, class), col_order)) %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_step() +
  geom_tile(aes(y = 0, height = Inf, fill = intervention), alpha = .2) +
  facet_wrap(~ school_class, ncol = 1) +
  scale_fill_manual(values = c(intervention_col, cbPalette[3:4], "white")) +
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(add = c(0, .1))) +
  labs(y = "Estimated number of new cases", title = "b") +
  theme_bw2() +
  theme(legend.title = element_blank(), axis.title.x = element_blank(),
        legend.position = "top") +
  guides(fill = guide_legend(nrow = 1))
  

cases_time_pl

descriptives_pl <- arrangeGrob(total_freq_pl, cases_time_pl, heights = c(6, 10), ncol = 1)
ggsave(plot = descriptives_pl, filename = "../results/redcap-descriptives.pdf", width = 16 / cm(1), height = 16 / cm(1))
```

### Comparing sim

```{r}
case_lab <- c("Confirmed (positive test result)", "Confirmed (isolation)", 
              "Suspected (known symptoms)", "Suspected (unknown symptoms)")
names(case_lab) <- c("confirmed", "isolated", "symptomatic", "unknown")

new_df <- df %>%
  mutate(class = recode(class, !!! classes_names),
         school_class = paste(school, class)) %>%
  rename(date = date_start) %>%
  group_by(school_class, date, suspected) %>%
  summarise(new_cases = n()) %>%
  ungroup() %>%
  mutate(suspected = recode(suspected, !!! case_lab),
         suspected = factor(suspected, levels = rev(case_lab))) 

comp_sim_pl <- sim_modeling_df %>%
  group_by(school_class, school, class, date) %>%
  summarise(new_cases = mean(new_cases)) %>%
  ungroup() %>%
  mutate(class = recode(class, !!! classes_names),
         school_class = factor(paste(school, class), col_order)) %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_bar(data = new_df, mapping = aes(fill = suspected), stat = "identity") +
  geom_step(aes(color = "Estimated average number of new cases after probabilistic simulation")) +
  facet_wrap(~ school_class, ncol = 1) +
  scale_fill_manual(values = (c(RColorBrewer::brewer.pal(9, "Purples")[c(6,4)], 
                                RColorBrewer::brewer.pal(9, "Greens")[c(6,4)])),
                    limits = case_lab) +
  scale_color_manual(values = "black") +
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(add = c(0, .1))) +
  labs(y = "Number of new cases", fill = "Confirmed and suspected number of new cases (observed)") +
  theme_bw2() +
  theme(legend.title = element_blank(), axis.title.x = element_blank(), legend.position = "top",
        legend.box = "vertical") 

comp_sim_pl

save_plot(comp_sim_pl, pdf_file = "../results/redcap-supp-descriptives.pdf", w = 16, h = 12)
```

### Table Time Series

```{r}
case_lab <- c("Confirmed (positive test result)", "Confirmed (isolation)", 
              "Suspected (known symptoms)", "Suspected (unknown symptoms)")
names(case_lab) <- c("confirmed", "isolated", "symptomatic", "unknown")

tbl <- df %>%
  mutate(school = gsub("School ", "", school),
         across(c(date_start, date_symptoms), function(x) format(x, "%m-%d")),
         across(c(date_start, date_symptoms), function(x) ifelse(is.na(x), "", as.character(x)))) %>%
  select(school, class, date_start, date_symptoms, suspected) %>%
  group_by(school, class) %>%
  arrange(date_start) %>%
  ungroup() %>%
  mutate(suspected = recode(suspected, !!! case_lab),
         class = recode(class, !!! classes_names))

tbl1 <- tbl %>%
  filter(school == as.character(1)) %>%
  select(-school) %>%
  as.matrix()

tbl2 <- tbl %>%
  filter(school == as.character(2)) %>%
  select(-school) %>%
  as.matrix()

print.xtable(xtable(tbl1),
             file = "../results/cases-time-series-1.tex",
             type = "latex",
             sanitize.text.function = identity,
             include.colnames = F,
             include.rownames = F,
             only.contents = T,
             hline.after = NULL)

print.xtable(xtable(tbl2),
             file = "../results/cases-time-series-2.tex",
             type = "latex",
             sanitize.text.function = identity,
             include.colnames = F,
             include.rownames = F,
             only.contents = T,
             hline.after = NULL)
```


### Summary table

```{r}
df %>%
  group_by(school, class, suspected) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  dcast(school + class ~ suspected) %>%
  mutate(class = factor(class, levels = c("Study (A)", "Study (B)", "Study", "Control")),
         across(c(confirmed, isolated, symptomatic, unknown), ~ ifelse(.x %>% is.na(), 0, .x)),
         total = confirmed + isolated + symptomatic + unknown)  %>%
  select(school, class, total, confirmed, isolated, symptomatic, unknown) %>%
  bind_rows(data.frame(school = "Total",
                       class = "Total",
                       total = sum(.$total),
                       confirmed = sum(.$confirmed),
                       isolated = sum(.$isolated),
                       symptomatic = sum(.$symptomatic),
                       unknown = sum(.$unknown))) %>%
  mutate(confirmed = confirmed + isolated,
         suspected = symptomatic + unknown) %>%
  select(school, class, confirmed, suspected, total) %>%
  as.matrix() %>%
  t()
```


### Molecular table

```{r}
cases <- df %>%
  filter(class != "Control") %>%
  mutate(study_week = week(date_start)) %>%
  group_by(school, study_week, suspected) %>%
  summarize(n()) %>%
  ungroup() %>%
  dcast(school + study_week ~ suspected) %>%
  mutate(across(c(confirmed, isolated, symptomatic, unknown), ~ ifelse(.x %>% is.na(), 0, .x)),
         positive_test_result = confirmed,
         confirmed = positive_test_result + isolated,
         suspected = symptomatic + unknown) %>%
  select(school, study_week, confirmed, positive_test_result, isolated, suspected, symptomatic, unknown) %>%
  group_by(school) %>%
  arrange(study_week) %>%
  mutate(study_week = 1:n()) %>%
  ungroup()

cases_tot <- cases %>%
  group_by(school) %>%
  summarise(across(-study_week, sum)) %>%
  ungroup() %>%
  mutate(study_week = 8)

cases <- rbind(cases, cases_tot) %>%
  group_by(school) %>%
  arrange(study_week) %>%
  ungroup()

n_class <- absences_df %>%
  filter(class != "Control") %>%
  group_by(school, class) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(school) %>%
  summarize(n_class = sum(n_class)) %>%
  ungroup()

absences <- absences_df %>%
  filter(class != "Control") %>%
  mutate(week = week(date)) %>%
  filter(week > 3) %>%
  left_join(full_df %>% 
              select(school, week, no_school) %>%
              group_by(school, week) %>%
              slice(1) %>%
              ungroup()) %>%
  filter(!no_school) %>%
  rename(study_week = week) %>%
  group_by(school, study_week) %>%
  summarize(n_tot_absent = sum(n_absent)) %>%
  ungroup() %>%
  group_by(school) %>%
  arrange(study_week) %>%
  mutate(study_week = 1:n()) %>%
  ungroup() %>%
  left_join(n_class) %>%
  mutate(`No. of students` = round((n_class * 5 - n_tot_absent) / 5)) %>%
  select(school, study_week, `No. of students`)

absences_mean <- absences %>%
  group_by(school) %>%
  summarise(across(-study_week, ~ round(mean(.x), 0))) %>%
  ungroup() %>%
  mutate(study_week = 8)

absences <- rbind(absences, absences_mean) %>%
  group_by(school) %>%
  arrange(study_week) %>%
  ungroup()
  

cases_air <- tibble(
  school = c(rep("School 1", 8), rep("School 2", 8)),
  study_week = c(1:8, 1:8),
  `Saliva samples` = c(21, 21+23, 26, 29, 20, 18, 15, 173,
                       17, 13+7, 14, 10, 11, 12, 5, 89),
  `Negative saliva` = NA,
  `Positive saliva` = c(1, 2, 0, 2, 6, 1, 0, 12,
                        1, 0, 2, 0, 1, 3, 0, 7),
  `Air samples` = NA,
  `Air samples (Vivas)` = c(4, 4, 5, 5, 5, 5, 5, 33,
                            4, 4, 4, 5, 4, 4, 5, 30),
  `Air samples (Coriolis)` = c(5, 5, 5, 5, 5, 5, 5, 35,
                               5, 5, 4, 5, 4, 5, 4, 32),
  `Negative air` = NA,
  `Positive air` = c(0, 0, 0, 2, 0, 0, 2, 4, 
                     1, 3, 0, 0, 1, 0, 0, 5),
  `Copies/l (Vivas)` = c("0", "0", "0", "2.46", "0", "0", "0.36", "",
                         "1.27", "2.68", "0", "0", "2.07", "0", "0", "") ,
  `Copies/l (Coriolis)` = c("0", "0", "0", "0", "0", "0", "0.12", "",
                            "0", "0.16", "0", "0", "0", "0", "0", ""),
  `Positive air samples on filter 1` = c(rep("", 7), 2, rep("", 7), 4),
  `Positive air samples on filter 2` = c(rep("", 7), 0, rep("", 7), 3)
) %>%
  mutate(`Negative saliva` = `Saliva samples` - `Positive saliva`,
         `Air samples` = `Air samples (Vivas)` + `Air samples (Coriolis)`,
         `Negative air` = `Air samples` - `Positive air`)

cases_mol <- left_join(left_join(absences, cases), cases_air) 

varnames <- c("No. of students", "Confirmed", "\\hphantom{00}Positive test result", "\\hphantom{00}Isolation",
              "Suspected", "\\hphantom{00}Known symptoms", "\\hphantom{00}Unknown symptoms",
              "Saliva samples", "\\hphantom{00}Negative", "\\hphantom{00}Positive", 
              "Air samples", "\\hphantom{00}Coriolis", "\\hphantom{00}Vivas", "\\hphantom{00}Negative", "\\hphantom{00}Positive", 
              "\\hphantom{0000}Vivas: Copies/l", "\\hphantom{0000}Coriolis: Copies/l",
              "Positive air samples on filter 1", "Positive air samples on filter 2")

mol_tbl_1 <- cases_mol %>%
  filter(school == "School 1") %>%
  select(-school) %>%
  melt("study_week") %>%
  dcast(variable ~ study_week) %>%
  as.matrix() 
mol_tbl_1[,1] <- varnames
mol_tbl_1[8,3] <- paste0(mol_tbl_1[8,3],"$^{\\ddag}$")

mol_tbl_1 %>%
  xtable() %>%
  print.xtable(
    file = "../results/redcapr-air-cases-1.tex",
    type = "latex",
    sanitize.text.function = identity,
    include.colnames = F,
    include.rownames = F,
    only.contents = T,
    hline.after = c(1,7,10,17))

mol_tbl_2 <- cases_mol %>%
  filter(school == "School 2") %>%
  select(-school) %>%
  melt("study_week") %>%
  dcast(variable ~ study_week) %>%
  as.matrix() 
mol_tbl_2[,1] <- varnames
mol_tbl_2[8,3] <- paste0(mol_tbl_2[8,3],"$^{\\ddag}$")

mol_tbl_2 %>%
  xtable() %>%
  print.xtable(
    file = "../results/redcapr-air-cases-2.tex",
    type = "latex",
    sanitize.text.function = identity,
    include.colnames = F,
    include.rownames = F,
    only.contents = T,
    hline.after = c(1,7,10,17))
```


### Molecular figure

```{r}
cases_mol_sum <- cases_mol %>%
  mutate(`Saliva samples` = ifelse(study_week == 2, `Saliva samples` / 2, `Saliva samples`),
         share_positive_air = 100 * `Positive air` / `Air samples`,
         share_positive_saliva = 100 * `Positive saliva` / `Saliva samples`,
         positive_copies_l = `Copies/l (Vivas)`) %>%
  select(school, study_week, share_positive_air, share_positive_saliva, positive_copies_l) %>%
  filter(study_week < 8) %>%
  mutate(positive_copies_l = as.numeric(positive_copies_l)) %>%
  mutate(intervention = ifelse(school == "School 1", ifelse(study_week <= 2, "Mask mandate",
                                                            ifelse(study_week <= 5, "No intervention",
                                                                   "Air cleaner")),
                               ifelse(study_week <= 4, "Mask mandate", 
                                      ifelse(study_week <= 5, "No intervention",
                                             "Air cleaner"))),
         intervention = factor(intervention, levels = c("Mask mandate", "No intervention", "Air cleaner"))) %>%
  group_by(intervention) %>%
  summarize(across(c(share_positive_saliva, share_positive_air, positive_copies_l), mean, na.rm = T)) %>%
  ungroup() 
  

mol_samples_pl <- cases_mol_sum %>%
  select(-positive_copies_l) %>%
  melt(c("intervention")) %>%
  mutate(variable = factor(ifelse(grepl("air", variable), "Air", "Saliva"), levels = c("Air", "Saliva"))) %>%
  ggplot(aes(x = as.integer(intervention), y = value, linetype = variable)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(1,2,3), labels = c("Mask mandate", "No intervention", "Air cleaner")) +
  scale_y_continuous(limits = c(0, 15), expand = c(0,0)) +
  #scale_color_manual(values = RColorBrewer::brewer.pal(3, "Set2")[c(2,3)]) +
  labs(y = "Proportion of ositive samples per week (%)", title = "a") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), legend.title = element_blank())

mol_samples_pl

mol_copies_pl <- cases_mol_sum %>%
  ggplot(aes(x = as.integer(intervention), y = positive_copies_l)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(1,2,3), labels = c("Mask mandate", "No intervention", "Air cleaner")) +
  scale_y_continuous(limits = c(0, 1.5), expand = c(0,0)) +
  scale_color_manual(values = RColorBrewer::brewer.pal(3, "Set2")[c(2,3)]) +
  labs(y = "Viral concentration (copies/l per week)", title = "b") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), legend.title = element_blank(), legend.position = "none", 
        plot.margin = unit(c(5.5, 15, 5.5, 5.5), units = "pt"))

mol_copies_pl

descriptives_mol_pl <- arrangeGrob(mol_samples_pl, mol_copies_pl, widths = c(9, 7),  nrow = 1)
ggsave(plot = descriptives_mol_pl, 
       filename = "../results/molecular-descriptives.pdf", 
       width = 16 / cm(1), height = 7 / cm(1))
```
